# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Choose_Game.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1440, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1440, 1000))
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cw1 = QtWidgets.QWidget(self.centralwidget)
        self.cw1.setGeometry(QtCore.QRect(70, 220, 271, 191))
        self.cw1.setObjectName("cw1")
        self.cw1_name = QtWidgets.QLabel(self.cw1)
        self.cw1_name.setGeometry(QtCore.QRect(17, 6, 231, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.cw1_name.setFont(font)
        self.cw1_name.setObjectName("cw1_name")
        self.cw1_name.setStyleSheet("color:#bad3e0")
        self.cw1_checkBox = QtWidgets.QCheckBox(self.cw1)
        self.cw1_checkBox.setGeometry(QtCore.QRect(16, 156, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.cw1_checkBox.setFont(font)
        self.cw1_checkBox.setObjectName("cw1_checkBox")
        self.cw1_img = QtWidgets.QLabel(self.cw1)
        self.cw1_img.setGeometry(QtCore.QRect(12, 40, 246, 115))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(65)
        self.cw1_img.setFont(font)
        self.cw1_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cw1_img.setObjectName("cw1_img")
        self.cw1_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")
        self.cw3 = QtWidgets.QWidget(self.centralwidget)
        self.cw3.setGeometry(QtCore.QRect(70, 440, 271, 191))
        self.cw3.setObjectName("cw3")
        self.cw3_name = QtWidgets.QLabel(self.cw3)
        self.cw3_name.setGeometry(QtCore.QRect(17, 6, 231, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.cw3_name.setFont(font)
        self.cw3_name.setObjectName("cw3_name")
        self.cw3_name.setStyleSheet("color:#bad3e0")
        self.cw3_checkBox = QtWidgets.QCheckBox(self.cw3)
        self.cw3_checkBox.setGeometry(QtCore.QRect(16, 156, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.cw3_checkBox.setFont(font)
        self.cw3_checkBox.setObjectName("cw3_checkBox")
        self.cw3_img = QtWidgets.QLabel(self.cw3)
        self.cw3_img.setGeometry(QtCore.QRect(12, 40, 246, 115))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(65)
        self.cw3_img.setFont(font)
        self.cw3_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cw3_img.setObjectName("cw3_img")
        self.cw3_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")
        self.cw5 = QtWidgets.QWidget(self.centralwidget)
        self.cw5.setGeometry(QtCore.QRect(70, 660, 271, 191))
        self.cw5.setObjectName("cw5")
        self.cw5_name = QtWidgets.QLabel(self.cw5)
        self.cw5_name.setGeometry(QtCore.QRect(17, 6, 231, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.cw5_name.setFont(font)
        self.cw5_name.setObjectName("cw5_name")
        self.cw5_name.setStyleSheet("color:#bad3e0")
        self.cw5_checkBox = QtWidgets.QCheckBox(self.cw5)
        self.cw5_checkBox.setGeometry(QtCore.QRect(16, 156, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.cw5_checkBox.setFont(font)
        self.cw5_checkBox.setObjectName("cw5_checkBox")
        self.cw5_img = QtWidgets.QLabel(self.cw5)
        self.cw5_img.setGeometry(QtCore.QRect(12, 40, 246, 115))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(65)
        self.cw5_img.setFont(font)
        self.cw5_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cw5_img.setObjectName("cw5_img")
        self.cw5_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")
        self.cw4 = QtWidgets.QWidget(self.centralwidget)
        self.cw4.setGeometry(QtCore.QRect(370, 440, 271, 191))
        self.cw4.setObjectName("cw4")
        self.cw4_name = QtWidgets.QLabel(self.cw4)
        self.cw4_name.setGeometry(QtCore.QRect(17, 6, 231, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.cw4_name.setFont(font)
        self.cw4_name.setObjectName("cw4_name")
        self.cw4_name.setStyleSheet("color:#bad3e0")
        self.cw4_checkBox = QtWidgets.QCheckBox(self.cw4)
        self.cw4_checkBox.setGeometry(QtCore.QRect(16, 156, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.cw4_checkBox.setFont(font)
        self.cw4_checkBox.setObjectName("cw4_checkBox")
        self.cw4_img = QtWidgets.QLabel(self.cw4)
        self.cw4_img.setGeometry(QtCore.QRect(12, 40, 246, 115))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(65)
        self.cw4_img.setFont(font)
        self.cw4_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cw4_img.setObjectName("cw4_img")
        self.cw4_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")


        self.cw6 = QtWidgets.QWidget(self.centralwidget)
        self.cw6.setGeometry(QtCore.QRect(370, 660, 271, 191))
        self.cw6.setObjectName("cw6")
        self.cw6_name = QtWidgets.QLabel(self.cw6)
        self.cw6_name.setGeometry(QtCore.QRect(17, 6, 231, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.cw6_name.setFont(font)
        self.cw6_name.setObjectName("cw6_name")
        self.cw6_name.setStyleSheet("color:#bad3e0")
        self.cw6_checkBox = QtWidgets.QCheckBox(self.cw6)
        self.cw6_checkBox.setGeometry(QtCore.QRect(16, 156, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.cw6_checkBox.setFont(font)
        self.cw6_checkBox.setObjectName("cw6_checkBox")
        self.cw6_img = QtWidgets.QLabel(self.cw6)
        self.cw6_img.setGeometry(QtCore.QRect(12, 40, 246, 115))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(65)
        self.cw6_img.setFont(font)
        self.cw6_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cw6_img.setObjectName("cw6_img")
        self.cw6_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")

        self.cw2 = QtWidgets.QWidget(self.centralwidget)
        self.cw2.setGeometry(QtCore.QRect(370, 220, 271, 191))
        self.cw2.setObjectName("cw2")
        self.cw2_name = QtWidgets.QLabel(self.cw2)
        self.cw2_name.setGeometry(QtCore.QRect(17, 6, 231, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.cw2_name.setFont(font)
        self.cw2_name.setObjectName("cw2_name")
        self.cw2_name.setStyleSheet("color:#bad3e0")
        self.cw2_checkBox = QtWidgets.QCheckBox(self.cw2)
        self.cw2_checkBox.setGeometry(QtCore.QRect(16, 156, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.cw2_checkBox.setFont(font)
        self.cw2_checkBox.setObjectName("cw2_checkBox")
        self.cw2_img = QtWidgets.QLabel(self.cw2)
        self.cw2_img.setGeometry(QtCore.QRect(12, 40, 246, 115))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(65)
        self.cw2_img.setFont(font)
        self.cw2_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cw2_img.setObjectName("cw2_img")
        self.cw2_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")


        self.Button_reflash = QtWidgets.QPushButton(self.centralwidget)
        self.Button_reflash.setGeometry(QtCore.QRect(270, 880, 171, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.Button_reflash.setFont(font)
        self.Button_reflash.setObjectName("Button_reflash")
        self.hw1 = QtWidgets.QWidget(self.centralwidget)
        self.hw1.setGeometry(QtCore.QRect(710, 160, 371, 51))
        self.hw1.setObjectName("hw1")
        self.hw1_name = QtWidgets.QLabel(self.hw1)
        self.hw1_name.setGeometry(QtCore.QRect(20, 10, 331, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.hw1_name.setFont(font)
        self.hw1_name.setObjectName("hw1_name")
        self.label_sign1 = QtWidgets.QLabel(self.centralwidget)
        self.label_sign1.setGeometry(QtCore.QRect(100, 110, 361, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_sign1.setFont(font)
        self.label_sign1.setObjectName("label_sign1")
        self.label_sign2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sign2.setGeometry(QtCore.QRect(210, 160, 361, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_sign2.setFont(font)
        self.label_sign2.setObjectName("label_sign2")
        self.label_chosen = QtWidgets.QLabel(self.centralwidget)
        self.label_chosen.setGeometry(QtCore.QRect(710, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_chosen.setFont(font)
        self.label_chosen.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_chosen.setObjectName("label_chosen")
        self.hw2 = QtWidgets.QWidget(self.centralwidget)
        self.hw2.setGeometry(QtCore.QRect(710, 230, 371, 51))
        self.hw2.setObjectName("hw2")
        self.hw2_name = QtWidgets.QLabel(self.hw2)
        self.hw2_name.setGeometry(QtCore.QRect(20, 10, 331, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.hw2_name.setFont(font)
        self.hw2_name.setObjectName("hw2_name")
        self.hw3 = QtWidgets.QWidget(self.centralwidget)
        self.hw3.setGeometry(QtCore.QRect(710, 300, 371, 51))
        self.hw3.setObjectName("hw3")
        self.hw3_name = QtWidgets.QLabel(self.hw3)
        self.hw3_name.setGeometry(QtCore.QRect(20, 10, 331, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.hw3_name.setFont(font)
        self.hw3_name.setObjectName("hw3_name")
        self.rw1 = QtWidgets.QWidget(self.centralwidget)
        self.rw1.setGeometry(QtCore.QRect(710, 440, 681, 141))
        self.rw1.setObjectName("rw1")
        self.rw1_img = QtWidgets.QLabel(self.rw1)
        self.rw1_img.setGeometry(QtCore.QRect(10, 10, 260, 121))
        self.rw1_img.setMinimumSize(QtCore.QSize(260, 121))
        self.rw1_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        font.setBold(False)
        font.setWeight(50)
        self.rw1_img.setFont(font)
        self.rw1_img.setAlignment(QtCore.Qt.AlignCenter)
        self.rw1_img.setObjectName("rw1_img")
        self.rw1_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")

        self.rw1_name = QtWidgets.QLabel(self.rw1)
        self.rw1_name.setGeometry(QtCore.QRect(280, 10, 381, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.rw1_name.setFont(font)
        self.rw1_name.setObjectName("rw1_name")
        self.rw1_name.setStyleSheet("color:#bad3e0")

        self.rw1_dev = QtWidgets.QLabel(self.rw1)
        self.rw1_dev.setGeometry(QtCore.QRect(280, 40, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rw1_dev.setFont(font)
        self.rw1_dev.setObjectName("rw1_dev")
        self.rw1_dev.setStyleSheet("color:#66c0f4")

        self.rw1_tags = QtWidgets.QLabel(self.rw1)
        self.rw1_tags.setGeometry(QtCore.QRect(280, 87, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw1_tags.setFont(font)
        self.rw1_tags.setObjectName("rw1_tags")
        self.rw1_tags.setStyleSheet("color:#bad3e0")

        self.rw1_tags_text = QtWidgets.QLabel(self.rw1)
        self.rw1_tags_text.setGeometry(QtCore.QRect(280, 112, 231, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw1_tags_text.setFont(font)
        self.rw1_tags_text.setObjectName("rw1_tags_text")
        self.rw1_tags_text.setStyleSheet("color:#66c0f4")


        self.rw1_or = QtWidgets.QLabel(self.rw1)
        self.rw1_or.setGeometry(QtCore.QRect(280, 64, 81, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw1_or.setFont(font)
        self.rw1_or.setObjectName("rw1_or")
        self.rw1_or.setStyleSheet("color:#bad3e0")

        self.rw1_or_text = QtWidgets.QLabel(self.rw1)
        self.rw1_or_text.setGeometry(QtCore.QRect(350, 66, 71, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw1_or_text.setFont(font)
        self.rw1_or_text.setObjectName("rw1_or_text")
        self.rw1_or_text.setStyleSheet("color:#66c0f4")


        self.rw1_price = QtWidgets.QLabel(self.rw1)
        self.rw1_price.setGeometry(QtCore.QRect(590, 55, 81, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rw1_price.setFont(font)
        self.rw1_price.setObjectName("rw1_price")
        self.label_recommend = QtWidgets.QLabel(self.centralwidget)
        self.label_recommend.setGeometry(QtCore.QRect(710, 390, 271, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_recommend.setFont(font)
        self.label_recommend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_recommend.setObjectName("label_recommend")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(8, 4, 191, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_title.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.rw2 = QtWidgets.QWidget(self.centralwidget)
        self.rw2.setGeometry(QtCore.QRect(710, 600, 681, 141))
        self.rw2.setObjectName("rw2")
        self.rw2_img = QtWidgets.QLabel(self.rw2)
        self.rw2_img.setGeometry(QtCore.QRect(10, 10, 260, 121))
        self.rw2_img.setMinimumSize(QtCore.QSize(260, 121))
        self.rw2_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        font.setBold(False)
        font.setWeight(50)
        self.rw2_img.setFont(font)
        self.rw2_img.setAlignment(QtCore.Qt.AlignCenter)
        self.rw2_img.setObjectName("rw2_img")
        self.rw2_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")

        self.rw2_name = QtWidgets.QLabel(self.rw2)
        self.rw2_name.setGeometry(QtCore.QRect(280, 10, 381, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.rw2_name.setFont(font)
        self.rw2_name.setObjectName("rw2_name")
        self.rw2_name.setStyleSheet("color:#bad3e0")

        self.rw2_dev = QtWidgets.QLabel(self.rw2)
        self.rw2_dev.setGeometry(QtCore.QRect(280, 40, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rw2_dev.setFont(font)
        self.rw2_dev.setObjectName("rw2_dev")
        self.rw2_dev.setStyleSheet("color:#66c0f4")

        self.rw2_tags = QtWidgets.QLabel(self.rw2)
        self.rw2_tags.setGeometry(QtCore.QRect(280, 87, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw2_tags.setFont(font)
        self.rw2_tags.setObjectName("rw2_tags")
        self.rw2_tags.setStyleSheet("color:#bad3e0")

        self.rw2_tags_text = QtWidgets.QLabel(self.rw2)
        self.rw2_tags_text.setGeometry(QtCore.QRect(280, 112, 231, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw2_tags_text.setFont(font)
        self.rw2_tags_text.setObjectName("rw2_tags_text")
        self.rw2_tags_text.setStyleSheet("color:#66c0f4")


        self.rw2_or = QtWidgets.QLabel(self.rw2)
        self.rw2_or.setGeometry(QtCore.QRect(280, 64, 81, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw2_or.setFont(font)
        self.rw2_or.setObjectName("rw2_or")
        self.rw2_or.setStyleSheet("color:#bad3e0")

        self.rw2_or_text = QtWidgets.QLabel(self.rw2)
        self.rw2_or_text.setGeometry(QtCore.QRect(350, 66, 71, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw2_or_text.setFont(font)
        self.rw2_or_text.setObjectName("rw2_or_text")
        self.rw2_or_text.setStyleSheet("color:#66c0f4")


        self.rw2_price = QtWidgets.QLabel(self.rw2)
        self.rw2_price.setGeometry(QtCore.QRect(590, 55, 81, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rw2_price.setFont(font)
        self.rw2_price.setObjectName("rw2_price")

        self.rw3 = QtWidgets.QWidget(self.centralwidget)
        self.rw3.setGeometry(QtCore.QRect(710, 760, 681, 141))
        self.rw3.setObjectName("rw3")
        self.rw3_img = QtWidgets.QLabel(self.rw3)
        self.rw3_img.setGeometry(QtCore.QRect(10, 10, 260, 121))
        self.rw3_img.setMinimumSize(QtCore.QSize(260, 121))
        self.rw3_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        font.setBold(False)
        font.setWeight(50)
        self.rw3_img.setFont(font)
        self.rw3_img.setAlignment(QtCore.Qt.AlignCenter)
        self.rw3_img.setObjectName("rw3_img")
        self.rw3_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")

        self.rw3_name = QtWidgets.QLabel(self.rw3)
        self.rw3_name.setGeometry(QtCore.QRect(280, 10, 381, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.rw3_name.setFont(font)
        self.rw3_name.setObjectName("rw3_name")
        self.rw3_name.setStyleSheet("color:#bad3e0")

        self.rw3_dev = QtWidgets.QLabel(self.rw3)
        self.rw3_dev.setGeometry(QtCore.QRect(280, 40, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rw3_dev.setFont(font)
        self.rw3_dev.setObjectName("rw3_dev")
        self.rw3_dev.setStyleSheet("color:#66c0f4")

        self.rw3_tags = QtWidgets.QLabel(self.rw3)
        self.rw3_tags.setGeometry(QtCore.QRect(280, 87, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw3_tags.setFont(font)
        self.rw3_tags.setObjectName("rw3_tags")
        self.rw3_tags.setStyleSheet("color:#bad3e0")

        self.rw3_tags_text = QtWidgets.QLabel(self.rw3)
        self.rw3_tags_text.setGeometry(QtCore.QRect(280, 112, 231, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw3_tags_text.setFont(font)
        self.rw3_tags_text.setObjectName("rw3_tags_text")
        self.rw3_tags_text.setStyleSheet("color:#66c0f4")


        self.rw3_or = QtWidgets.QLabel(self.rw3)
        self.rw3_or.setGeometry(QtCore.QRect(280, 64, 81, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw3_or.setFont(font)
        self.rw3_or.setObjectName("rw3_or")
        self.rw3_or.setStyleSheet("color:#bad3e0")

        self.rw3_or_text = QtWidgets.QLabel(self.rw3)
        self.rw3_or_text.setGeometry(QtCore.QRect(350, 66, 71, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rw3_or_text.setFont(font)
        self.rw3_or_text.setObjectName("rw3_or_text")
        self.rw3_or_text.setStyleSheet("color:#66c0f4")


        self.rw3_price = QtWidgets.QLabel(self.rw3)
        self.rw3_price.setGeometry(QtCore.QRect(590, 55, 81, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rw3_price.setFont(font)
        self.rw3_price.setObjectName("rw3_price")

        self.Button_back = QtWidgets.QPushButton(self.centralwidget)
        self.Button_back.setGeometry(QtCore.QRect(1130, 180, 191, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        self.Button_back.setFont(font)
        self.Button_back.setObjectName("Button_back")
        self.Button_go = QtWidgets.QPushButton(self.centralwidget)
        self.Button_go.setGeometry(QtCore.QRect(1130, 260, 191, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        self.Button_go.setFont(font)
        self.Button_go.setObjectName("Button_go")

        self.cw1.setStyleSheet("background-color:#263550;border-radius:15px")
        self.cw2.setStyleSheet("background-color:#263550;border-radius:15px")
        self.cw3.setStyleSheet("background-color:#263550;border-radius:15px")
        self.cw4.setStyleSheet("background-color:#263550;border-radius:15px")
        self.cw5.setStyleSheet("background-color:#263550;border-radius:15px")
        self.cw6.setStyleSheet("background-color:#263550;border-radius:15px")
        self.hw1.setStyleSheet("background-color:#263550;border-radius:15px")
        self.hw2.setStyleSheet("background-color:#263550;border-radius:15px")
        self.hw3.setStyleSheet("background-color:#263550;border-radius:15px")
        self.rw1.setStyleSheet("background-color:#263550;border-radius:15px")
        self.rw2.setStyleSheet("background-color:#263550;border-radius:15px")
        self.rw3.setStyleSheet("background-color:#263550;border-radius:15px")
        self.Button_reflash.setStyleSheet("QPushButton{color:white;background-color:#263550;border-style:solid; border-radius:10px}"
                                       "QPushButton:hover{color:white;background-color:#495976;border-style:solid; border-radius:10px}"
                                       "QPushButton:Pressed{color:white;background-color:#667288;border-style:solid; border-radius:10px}"
                                          "QPushButton:disabled{color:#464e5c;background-color:#263550;border-style:solid; border-radius:10px}")
        self.Button_back.setStyleSheet("QPushButton{color:white;background-color:#263550;border-style:solid; border-radius:10px}"
                                       "QPushButton:hover{color:white;background-color:#495976;border-style:solid; border-radius:10px}"
                                       "QPushButton:Pressed{color:white;background-color:#667288;border-style:solid; border-radius:10px}"
                                       "QPushButton:disabled{color:#464e5c;background-color:#263550;border-style:solid; border-radius:10px}")
        self.Button_go.setStyleSheet("QPushButton{color:white;background-color:#263550;border-style:solid; border-radius:10px}"
                                       "QPushButton:hover{color:white;background-color:#495976;border-style:solid; border-radius:10px}"
                                       "QPushButton:Pressed{color:white;background-color:#667288;border-style:solid; border-radius:10px}"
                                     "QPushButton:disabled{color:#464e5c;background-color:#263550;border-style:solid; border-radius:10px}")
        self.cw1_checkBox.setStyleSheet("QCheckBox{color:#66c0f4}"
                                        "QCheckBox:disabled{color:#464e5c}")
        self.cw2_checkBox.setStyleSheet("QCheckBox{color:#66c0f4}"
                                        "QCheckBox:disabled{color:#464e5c}")
        self.cw3_checkBox.setStyleSheet("QCheckBox{color:#66c0f4}"
                                        "QCheckBox:disabled{color:#464e5c}")
        self.cw4_checkBox.setStyleSheet("QCheckBox{color:#66c0f4}"
                                        "QCheckBox:disabled{color:#464e5c}")
        self.cw5_checkBox.setStyleSheet("QCheckBox{color:#66c0f4}"
                                        "QCheckBox:disabled{color:#464e5c}")
        self.cw6_checkBox.setStyleSheet("QCheckBox{color:#66c0f4}"
                                        "QCheckBox:disabled{color:#464e5c}")



        self.label_chosen.setStyleSheet("color:#a8bbde")
        self.label_recommend.setStyleSheet("color:#a8bbde")
        self.label_sign1.setStyleSheet("color:#a8bbde")
        self.label_sign2.setStyleSheet("color:#a8bbde")
        self.hw1_name.setStyleSheet("color:#464e5c")
        self.hw2_name.setStyleSheet("color:#464e5c")
        self.hw3_name.setStyleSheet("color:#464e5c")
        self.rw1_price.setStyleSheet("color:#809996")
        self.rw2_price.setStyleSheet("color:#809996")
        self.rw3_price.setStyleSheet("color:#809996")


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.cw1_name.setText(_translate("MainWindow", "Game Name"))
        self.cw1_checkBox.setText(_translate("MainWindow", "我喜欢/玩过这款游戏"))
        self.cw1_img.setText(_translate("MainWindow", "IMG"))
        self.cw2_name.setText(_translate("MainWindow", "Game Name"))
        self.cw2_checkBox.setText(_translate("MainWindow", "我喜欢/玩过这款游戏"))
        self.cw2_img.setText(_translate("MainWindow", "IMG"))
        self.cw3_name.setText(_translate("MainWindow", "Game Name"))
        self.cw3_checkBox.setText(_translate("MainWindow", "我喜欢/玩过这款游戏"))
        self.cw3_img.setText(_translate("MainWindow", "IMG"))
        self.cw4_name.setText(_translate("MainWindow", "Game Name"))
        self.cw4_checkBox.setText(_translate("MainWindow", "我喜欢/玩过这款游戏"))
        self.cw4_img.setText(_translate("MainWindow", "IMG"))
        self.cw5_name.setText(_translate("MainWindow", "Game Name"))
        self.cw5_checkBox.setText(_translate("MainWindow", "我喜欢/玩过这款游戏"))
        self.cw5_img.setText(_translate("MainWindow", "IMG"))
        self.cw6_name.setText(_translate("MainWindow", "Game Name"))
        self.cw6_checkBox.setText(_translate("MainWindow", "我喜欢/玩过这款游戏"))
        self.cw6_img.setText(_translate("MainWindow", "IMG"))

        self.Button_reflash.setText(_translate("MainWindow", "换一波游戏"))
        self.hw1_name.setText(_translate("MainWindow", "Unknow"))
        self.label_sign1.setText(_translate("MainWindow", "选择3款您喜欢/玩过的游戏"))
        self.label_sign2.setText(_translate("MainWindow", "我们将为您推荐相似的游戏"))
        self.label_chosen.setText(_translate("MainWindow", "已选择的游戏↓"))
        self.hw2_name.setText(_translate("MainWindow", "Unknow"))
        self.hw3_name.setText(_translate("MainWindow", "Unknow"))
        self.rw1_img.setText(_translate("MainWindow", "IMG"))
        self.rw1_name.setText(_translate("MainWindow", "Game Name"))
        self.rw1_dev.setText(_translate("MainWindow", "developer"))
        self.rw1_tags.setText(_translate("MainWindow", "标签："))
        self.rw1_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.rw1_or.setText(_translate("MainWindow", "总体评价："))
        self.rw1_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.rw1_price.setText(_translate("MainWindow", "￥233"))

        self.rw2_img.setText(_translate("MainWindow", "IMG"))
        self.rw2_name.setText(_translate("MainWindow", "Game Name"))
        self.rw2_dev.setText(_translate("MainWindow", "developer"))
        self.rw2_tags.setText(_translate("MainWindow", "标签："))
        self.rw2_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.rw2_or.setText(_translate("MainWindow", "总体评价："))
        self.rw2_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.rw2_price.setText(_translate("MainWindow", "￥233"))

        self.rw3_img.setText(_translate("MainWindow", "IMG"))
        self.rw3_name.setText(_translate("MainWindow", "Game Name"))
        self.rw3_dev.setText(_translate("MainWindow", "developer"))
        self.rw3_tags.setText(_translate("MainWindow", "标签："))
        self.rw3_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.rw3_or.setText(_translate("MainWindow", "总体评价："))
        self.rw3_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.rw3_price.setText(_translate("MainWindow", "￥233"))

        self.label_recommend.setText(_translate("MainWindow", "我们为您推荐的游戏↓"))
        self.label_title.setText(_translate("MainWindow", "Steam推荐 - Choose Game"))
        self.Button_back.setText(_translate("MainWindow", "重选"))
        self.Button_go.setText(_translate("MainWindow", "计算推荐游戏"))
