# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_top.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1440, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1440, 1000))
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tw1 = QtWidgets.QWidget(self.centralwidget)
        self.tw1.setGeometry(QtCore.QRect(585, 450, 270, 280))
        self.tw1.setMinimumSize(QtCore.QSize(270, 280))
        self.tw1.setMaximumSize(QtCore.QSize(270, 280))
        self.tw1.setObjectName("tw1")
        self.tw1_dev = QtWidgets.QLabel(self.tw1)
        self.tw1_dev.setGeometry(QtCore.QRect(10, 34, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.tw1_dev.setFont(font)
        self.tw1_dev.setObjectName("tw1_dev")
        self.tw1_dev.setStyleSheet("color:#66c0f4")

        self.tw1_name = QtWidgets.QLabel(self.tw1)
        self.tw1_name.setGeometry(QtCore.QRect(10, 4, 241, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw1_name.setFont(font)
        self.tw1_name.setObjectName("tw1_name")
        self.tw1_name.setStyleSheet("color:#bad3e0")

        self.tw1_tags_text = QtWidgets.QLabel(self.tw1)
        self.tw1_tags_text.setGeometry(QtCore.QRect(10, 250, 231, 20))
        self.tw1_tags_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw1_tags_text.setFont(font)
        self.tw1_tags_text.setObjectName("tw1_tags_text")
        self.tw1_tags = QtWidgets.QLabel(self.tw1)
        self.tw1_tags.setGeometry(QtCore.QRect(10, 228, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw1_tags.setFont(font)
        self.tw1_tags.setObjectName("tw1_tags")
        self.tw1_tags.setStyleSheet("color:#bad3e0")

        self.tw1_or = QtWidgets.QLabel(self.tw1)
        self.tw1_or.setGeometry(QtCore.QRect(10, 184, 81, 20))
        self.tw1_or.setStyleSheet("color:#bad3e0")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw1_or.setFont(font)
        self.tw1_or.setObjectName("tw1_or")
        self.tw1_or_text = QtWidgets.QLabel(self.tw1)
        self.tw1_or_text.setGeometry(QtCore.QRect(10, 206, 101, 20))
        self.tw1_or_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw1_or_text.setFont(font)
        self.tw1_or_text.setObjectName("tw1_or_text")
        self.tw1_img = QtWidgets.QLabel(self.tw1)
        self.tw1_img.setGeometry(QtCore.QRect(5, 58, 260, 121))
        self.tw1_img.setMinimumSize(QtCore.QSize(260, 121))
        self.tw1_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        self.tw1_img.setFont(font)
        self.tw1_img.setAlignment(QtCore.Qt.AlignCenter)
        self.tw1_img.setObjectName("tw1_img")
        self.tw1_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")
        self.tw1_price = QtWidgets.QLabel(self.tw1)
        self.tw1_price.setGeometry(QtCore.QRect(182, 190, 85, 35))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw1_price.setFont(font)
        self.tw1_price.setObjectName("tw1_price")
        self.tw1_price.setStyleSheet("color:#678090")

        self.tw2 = QtWidgets.QWidget(self.centralwidget)
        self.tw2.setGeometry(QtCore.QRect(305, 498, 270, 280))
        self.tw2.setMinimumSize(QtCore.QSize(270, 280))
        self.tw2.setMaximumSize(QtCore.QSize(270, 280))
        self.tw2.setObjectName("tw2")
        self.tw2_dev = QtWidgets.QLabel(self.tw2)
        self.tw2_dev.setGeometry(QtCore.QRect(10, 34, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.tw2_dev.setFont(font)
        self.tw2_dev.setObjectName("tw2_dev")
        self.tw2_dev.setStyleSheet("color:#66c0f4")

        self.tw2_name = QtWidgets.QLabel(self.tw2)
        self.tw2_name.setGeometry(QtCore.QRect(10, 4, 241, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw2_name.setFont(font)
        self.tw2_name.setObjectName("tw2_name")
        self.tw2_name.setStyleSheet("color:#bad3e0")

        self.tw2_tags_text = QtWidgets.QLabel(self.tw2)
        self.tw2_tags_text.setGeometry(QtCore.QRect(10, 250, 231, 20))
        self.tw2_tags_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw2_tags_text.setFont(font)
        self.tw2_tags_text.setObjectName("tw2_tags_text")
        self.tw2_tags = QtWidgets.QLabel(self.tw2)
        self.tw2_tags.setGeometry(QtCore.QRect(10, 228, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw2_tags.setFont(font)
        self.tw2_tags.setObjectName("tw2_tags")
        self.tw2_tags.setStyleSheet("color:#bad3e0")

        self.tw2_or = QtWidgets.QLabel(self.tw2)
        self.tw2_or.setGeometry(QtCore.QRect(10, 184, 81, 20))
        self.tw2_or.setStyleSheet("color:#bad3e0")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw2_or.setFont(font)
        self.tw2_or.setObjectName("tw2_or")
        self.tw2_or_text = QtWidgets.QLabel(self.tw2)
        self.tw2_or_text.setGeometry(QtCore.QRect(10, 206, 101, 20))
        self.tw2_or_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw2_or_text.setFont(font)
        self.tw2_or_text.setObjectName("tw2_or_text")
        self.tw2_img = QtWidgets.QLabel(self.tw2)
        self.tw2_img.setGeometry(QtCore.QRect(5, 58, 260, 121))
        self.tw2_img.setMinimumSize(QtCore.QSize(260, 121))
        self.tw2_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        self.tw2_img.setFont(font)
        self.tw2_img.setAlignment(QtCore.Qt.AlignCenter)
        self.tw2_img.setObjectName("tw2_img")
        self.tw2_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")
        self.tw2_price = QtWidgets.QLabel(self.tw2)
        self.tw2_price.setGeometry(QtCore.QRect(182, 190, 85, 35))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw2_price.setFont(font)
        self.tw2_price.setObjectName("tw2_price")
        self.tw2_price.setStyleSheet("color:#678090")

        self.tw3 = QtWidgets.QWidget(self.centralwidget)
        self.tw3.setGeometry(QtCore.QRect(865, 545, 270, 280))
        self.tw3.setMinimumSize(QtCore.QSize(270, 280))
        self.tw3.setMaximumSize(QtCore.QSize(270, 280))
        self.tw3.setObjectName("tw3")
        self.tw3_dev = QtWidgets.QLabel(self.tw3)
        self.tw3_dev.setGeometry(QtCore.QRect(10, 34, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.tw3_dev.setFont(font)
        self.tw3_dev.setObjectName("tw3_dev")
        self.tw3_dev.setStyleSheet("color:#66c0f4")

        self.tw3_name = QtWidgets.QLabel(self.tw3)
        self.tw3_name.setGeometry(QtCore.QRect(10, 4, 241, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw3_name.setFont(font)
        self.tw3_name.setObjectName("tw3_name")
        self.tw3_name.setStyleSheet("color:#bad3e0")

        self.tw3_tags_text = QtWidgets.QLabel(self.tw3)
        self.tw3_tags_text.setGeometry(QtCore.QRect(10, 250, 231, 20))
        self.tw3_tags_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw3_tags_text.setFont(font)
        self.tw3_tags_text.setObjectName("tw3_tags_text")
        self.tw3_tags = QtWidgets.QLabel(self.tw3)
        self.tw3_tags.setGeometry(QtCore.QRect(10, 228, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw3_tags.setFont(font)
        self.tw3_tags.setObjectName("tw3_tags")
        self.tw3_tags.setStyleSheet("color:#bad3e0")

        self.tw3_or = QtWidgets.QLabel(self.tw3)
        self.tw3_or.setGeometry(QtCore.QRect(10, 184, 81, 20))
        self.tw3_or.setStyleSheet("color:#bad3e0")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw3_or.setFont(font)
        self.tw3_or.setObjectName("tw3_or")
        self.tw3_or_text = QtWidgets.QLabel(self.tw3)
        self.tw3_or_text.setGeometry(QtCore.QRect(10, 206, 101, 20))
        self.tw3_or_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw3_or_text.setFont(font)
        self.tw3_or_text.setObjectName("tw3_or_text")
        self.tw3_img = QtWidgets.QLabel(self.tw3)
        self.tw3_img.setGeometry(QtCore.QRect(5, 58, 260, 121))
        self.tw3_img.setMinimumSize(QtCore.QSize(260, 121))
        self.tw3_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        self.tw3_img.setFont(font)
        self.tw3_img.setAlignment(QtCore.Qt.AlignCenter)
        self.tw3_img.setObjectName("tw3_img")
        self.tw3_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")
        self.tw3_price = QtWidgets.QLabel(self.tw3)
        self.tw3_price.setGeometry(QtCore.QRect(182, 190, 85, 35))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw3_price.setFont(font)
        self.tw3_price.setObjectName("tw3_price")
        self.tw3_price.setStyleSheet("color:#678090")

        self.tw4 = QtWidgets.QWidget(self.centralwidget)
        self.tw4.setGeometry(QtCore.QRect(25, 581, 270, 280))
        self.tw4.setMinimumSize(QtCore.QSize(270, 280))
        self.tw4.setMaximumSize(QtCore.QSize(270, 280))
        self.tw4.setObjectName("tw4")
        self.tw4_dev = QtWidgets.QLabel(self.tw4)
        self.tw4_dev.setGeometry(QtCore.QRect(10, 34, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.tw4_dev.setFont(font)
        self.tw4_dev.setObjectName("tw4_dev")
        self.tw4_dev.setStyleSheet("color:#66c0f4")

        self.tw4_name = QtWidgets.QLabel(self.tw4)
        self.tw4_name.setGeometry(QtCore.QRect(10, 4, 241, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw4_name.setFont(font)
        self.tw4_name.setObjectName("tw4_name")
        self.tw4_name.setStyleSheet("color:#bad3e0")

        self.tw4_tags_text = QtWidgets.QLabel(self.tw4)
        self.tw4_tags_text.setGeometry(QtCore.QRect(10, 250, 231, 20))
        self.tw4_tags_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw4_tags_text.setFont(font)
        self.tw4_tags_text.setObjectName("tw4_tags_text")
        self.tw4_tags = QtWidgets.QLabel(self.tw4)
        self.tw4_tags.setGeometry(QtCore.QRect(10, 228, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw4_tags.setFont(font)
        self.tw4_tags.setObjectName("tw4_tags")
        self.tw4_tags.setStyleSheet("color:#bad3e0")

        self.tw4_or = QtWidgets.QLabel(self.tw4)
        self.tw4_or.setGeometry(QtCore.QRect(10, 184, 81, 20))
        self.tw4_or.setStyleSheet("color:#bad3e0")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw4_or.setFont(font)
        self.tw4_or.setObjectName("tw4_or")
        self.tw4_or_text = QtWidgets.QLabel(self.tw4)
        self.tw4_or_text.setGeometry(QtCore.QRect(10, 206, 101, 20))
        self.tw4_or_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw4_or_text.setFont(font)
        self.tw4_or_text.setObjectName("tw4_or_text")
        self.tw4_img = QtWidgets.QLabel(self.tw4)
        self.tw4_img.setGeometry(QtCore.QRect(5, 58, 260, 121))
        self.tw4_img.setMinimumSize(QtCore.QSize(260, 121))
        self.tw4_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        self.tw4_img.setFont(font)
        self.tw4_img.setAlignment(QtCore.Qt.AlignCenter)
        self.tw4_img.setObjectName("tw4_img")
        self.tw4_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")
        self.tw4_price = QtWidgets.QLabel(self.tw4)
        self.tw4_price.setGeometry(QtCore.QRect(182, 190, 85, 35))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw4_price.setFont(font)
        self.tw4_price.setObjectName("tw4_price")
        self.tw4_price.setStyleSheet("color:#678090")


        self.tw5 = QtWidgets.QWidget(self.centralwidget)
        self.tw5.setGeometry(QtCore.QRect(1145, 605, 270, 280))
        self.tw5.setMinimumSize(QtCore.QSize(270, 280))
        self.tw5.setMaximumSize(QtCore.QSize(270, 280))
        self.tw5.setObjectName("tw5")
        self.tw5_dev = QtWidgets.QLabel(self.tw5)
        self.tw5_dev.setGeometry(QtCore.QRect(10, 34, 241, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.tw5_dev.setFont(font)
        self.tw5_dev.setObjectName("tw5_dev")
        self.tw5_dev.setStyleSheet("color:#66c0f4")

        self.tw5_name = QtWidgets.QLabel(self.tw5)
        self.tw5_name.setGeometry(QtCore.QRect(10, 4, 241, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw5_name.setFont(font)
        self.tw5_name.setObjectName("tw5_name")
        self.tw5_name.setStyleSheet("color:#bad3e0")

        self.tw5_tags_text = QtWidgets.QLabel(self.tw5)
        self.tw5_tags_text.setGeometry(QtCore.QRect(10, 250, 231, 20))
        self.tw5_tags_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw5_tags_text.setFont(font)
        self.tw5_tags_text.setObjectName("tw5_tags_text")
        self.tw5_tags = QtWidgets.QLabel(self.tw5)
        self.tw5_tags.setGeometry(QtCore.QRect(10, 228, 51, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw5_tags.setFont(font)
        self.tw5_tags.setObjectName("tw5_tags")
        self.tw5_tags.setStyleSheet("color:#bad3e0")

        self.tw5_or = QtWidgets.QLabel(self.tw5)
        self.tw5_or.setGeometry(QtCore.QRect(10, 184, 81, 20))
        self.tw5_or.setStyleSheet("color:#bad3e0")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw5_or.setFont(font)
        self.tw5_or.setObjectName("tw5_or")
        self.tw5_or_text = QtWidgets.QLabel(self.tw5)
        self.tw5_or_text.setGeometry(QtCore.QRect(10, 206, 101, 20))
        self.tw5_or_text.setStyleSheet("color:#66c0f4")

        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw5_or_text.setFont(font)
        self.tw5_or_text.setObjectName("tw5_or_text")
        self.tw5_img = QtWidgets.QLabel(self.tw5)
        self.tw5_img.setGeometry(QtCore.QRect(5, 58, 260, 121))
        self.tw5_img.setMinimumSize(QtCore.QSize(260, 121))
        self.tw5_img.setMaximumSize(QtCore.QSize(260, 121))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(80)
        self.tw5_img.setFont(font)
        self.tw5_img.setAlignment(QtCore.Qt.AlignCenter)
        self.tw5_img.setObjectName("tw5_img")
        self.tw5_img.setStyleSheet("color:#495976;background:#313e54;border-radius:10px")

        self.tw5_price = QtWidgets.QLabel(self.tw5)
        self.tw5_price.setGeometry(QtCore.QRect(182, 190, 85, 35))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(True)
        self.tw5_price.setFont(font)
        self.tw5_price.setObjectName("tw5_price")
        self.tw5_price.setStyleSheet("color:#678090")

        self.tw6 = QtWidgets.QWidget(self.centralwidget)
        self.tw6.setGeometry(QtCore.QRect(255, 100, 930, 60))
        self.tw6.setObjectName("tw6")
        self.tw6.setStyleSheet("background:#263550;border-radius:10px")

        self.tw6_top = QtWidgets.QLabel(self.tw6)
        self.tw6_top.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        self.tw6_top.setFont(font)
        self.tw6_top.setObjectName("tw6_top")
        self.tw6_top.setStyleSheet("color:#809996")

        self.tw6_name = QtWidgets.QLabel(self.tw6)
        self.tw6_name.setGeometry(QtCore.QRect(170, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw6_name.setFont(font)
        self.tw6_name.setObjectName("tw6_name")
        self.tw6_name.setStyleSheet("color:#bad3e0")

        self.tw6_or_text = QtWidgets.QLabel(self.tw6)
        self.tw6_or_text.setGeometry(QtCore.QRect(750, 7, 61, 20))


        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw6_or_text.setFont(font)
        self.tw6_or_text.setObjectName("tw6_or_text")
        self.tw6_or_text.setStyleSheet("color:#bad3e0")

        self.tw6_tags_text = QtWidgets.QLabel(self.tw6)
        self.tw6_tags_text.setGeometry(QtCore.QRect(630, 33, 181, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw6_tags_text.setFont(font)
        self.tw6_tags_text.setObjectName("tw6_tags_text")
        self.tw6_tags_text.setStyleSheet("color:#66c0f4")
        self.tw6_price = QtWidgets.QLabel(self.tw6)
        self.tw6_price.setGeometry(QtCore.QRect(830, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw6_price.setFont(font)
        self.tw6_price.setObjectName("tw6_price")
        self.tw6_price.setStyleSheet("color:#678090")


        self.tw7 = QtWidgets.QWidget(self.centralwidget)
        self.tw7.setGeometry(QtCore.QRect(255, 170, 930, 60))
        self.tw7.setObjectName("tw7")
        self.tw7.setStyleSheet("background:#394760;border-radius:10px")
        self.tw7_top = QtWidgets.QLabel(self.tw7)
        self.tw7_top.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        self.tw7_top.setFont(font)
        self.tw7_top.setObjectName("tw7_top")
        self.tw7_top.setStyleSheet("color:#809996")

        self.tw7_name = QtWidgets.QLabel(self.tw7)
        self.tw7_name.setGeometry(QtCore.QRect(170, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw7_name.setFont(font)
        self.tw7_name.setObjectName("tw7_name")
        self.tw7_name.setStyleSheet("color:#bad3e0")

        self.tw7_or_text = QtWidgets.QLabel(self.tw7)
        self.tw7_or_text.setGeometry(QtCore.QRect(750, 7, 61, 20))


        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw7_or_text.setFont(font)
        self.tw7_or_text.setObjectName("tw7_or_text")
        self.tw7_or_text.setStyleSheet("color:#bad3e0")

        self.tw7_tags_text = QtWidgets.QLabel(self.tw7)
        self.tw7_tags_text.setGeometry(QtCore.QRect(630, 33, 181, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw7_tags_text.setFont(font)
        self.tw7_tags_text.setObjectName("tw7_tags_text")
        self.tw7_tags_text.setStyleSheet("color:#66c0f4")

        self.tw7_price = QtWidgets.QLabel(self.tw7)
        self.tw7_price.setGeometry(QtCore.QRect(830, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw7_price.setFont(font)
        self.tw7_price.setObjectName("tw7_price")
        self.tw7_price.setStyleSheet("color:#678090")

        self.tw8 = QtWidgets.QWidget(self.centralwidget)
        self.tw8.setGeometry(QtCore.QRect(255, 240, 930, 60))
        self.tw8.setObjectName("tw8")
        self.tw8.setStyleSheet("background:#263550;border-radius:10px")
        self.tw8_top = QtWidgets.QLabel(self.tw8)
        self.tw8_top.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        self.tw8_top.setFont(font)
        self.tw8_top.setObjectName("tw8_top")
        self.tw8_top.setStyleSheet("color:#809996")

        self.tw8_name = QtWidgets.QLabel(self.tw8)
        self.tw8_name.setGeometry(QtCore.QRect(170, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw8_name.setFont(font)
        self.tw8_name.setObjectName("tw8_name")
        self.tw8_name.setStyleSheet("color:#bad3e0")

        self.tw8_or_text = QtWidgets.QLabel(self.tw8)
        self.tw8_or_text.setGeometry(QtCore.QRect(750, 7, 61, 20))


        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw8_or_text.setFont(font)
        self.tw8_or_text.setObjectName("tw8_or_text")
        self.tw8_or_text.setStyleSheet("color:#bad3e0")

        self.tw8_tags_text = QtWidgets.QLabel(self.tw8)
        self.tw8_tags_text.setGeometry(QtCore.QRect(630, 33, 181, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw8_tags_text.setFont(font)
        self.tw8_tags_text.setObjectName("tw8_tags_text")
        self.tw8_tags_text.setStyleSheet("color:#66c0f4")

        self.tw8_price = QtWidgets.QLabel(self.tw8)
        self.tw8_price.setGeometry(QtCore.QRect(830, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw8_price.setFont(font)
        self.tw8_price.setObjectName("tw8_price")
        self.tw8_price.setStyleSheet("color:#678090")

        self.tw9 = QtWidgets.QWidget(self.centralwidget)
        self.tw9.setGeometry(QtCore.QRect(255, 310, 930, 60))
        self.tw9.setObjectName("tw9")
        self.tw9.setStyleSheet("background:#394760;border-radius:10px")
        self.tw9_top = QtWidgets.QLabel(self.tw9)
        self.tw9_top.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        self.tw9_top.setFont(font)
        self.tw9_top.setObjectName("tw9_top")
        self.tw9_top.setStyleSheet("color:#809996")

        self.tw9_name = QtWidgets.QLabel(self.tw9)
        self.tw9_name.setGeometry(QtCore.QRect(170, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw9_name.setFont(font)
        self.tw9_name.setObjectName("tw9_name")
        self.tw9_name.setStyleSheet("color:#bad3e0")

        self.tw9_or_text = QtWidgets.QLabel(self.tw9)
        self.tw9_or_text.setGeometry(QtCore.QRect(750, 7, 61, 20))


        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw9_or_text.setFont(font)
        self.tw9_or_text.setObjectName("tw9_or_text")
        self.tw9_or_text.setStyleSheet("color:#bad3e0")

        self.tw9_tags_text = QtWidgets.QLabel(self.tw9)
        self.tw9_tags_text.setGeometry(QtCore.QRect(630, 33, 181, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw9_tags_text.setFont(font)
        self.tw9_tags_text.setObjectName("tw9_tags_text")
        self.tw9_tags_text.setStyleSheet("color:#66c0f4")

        self.tw9_price = QtWidgets.QLabel(self.tw9)
        self.tw9_price.setGeometry(QtCore.QRect(830, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw9_price.setFont(font)
        self.tw9_price.setObjectName("tw9_price")
        self.tw9_price.setStyleSheet("color:#678090")

        self.tw10 = QtWidgets.QWidget(self.centralwidget)
        self.tw10.setGeometry(QtCore.QRect(255, 380, 930, 60))
        self.tw10.setObjectName("tw10")
        self.tw10.setStyleSheet("background:#263550;border-radius:10px")


        self.tw10_top = QtWidgets.QLabel(self.tw10)
        self.tw10_top.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        self.tw10_top.setFont(font)
        self.tw10_top.setObjectName("tw10_top")
        self.tw10_top.setStyleSheet("color:#809996")

        self.tw10_name = QtWidgets.QLabel(self.tw10)
        self.tw10_name.setGeometry(QtCore.QRect(170, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(17)
        self.tw10_name.setFont(font)
        self.tw10_name.setObjectName("tw10_name")
        self.tw10_name.setStyleSheet("color:#bad3e0")

        self.tw10_or_text = QtWidgets.QLabel(self.tw10)
        self.tw10_or_text.setGeometry(QtCore.QRect(750, 7, 61, 20))


        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw10_or_text.setFont(font)
        self.tw10_or_text.setObjectName("tw10_or_text")
        self.tw10_or_text.setStyleSheet("color:#bad3e0")

        self.tw10_tags_text = QtWidgets.QLabel(self.tw10)
        self.tw10_tags_text.setGeometry(QtCore.QRect(630, 33, 181, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.tw10_tags_text.setFont(font)
        self.tw10_tags_text.setObjectName("tw10_tags_text")
        self.tw10_tags_text.setStyleSheet("color:#66c0f4")

        self.tw10_price = QtWidgets.QLabel(self.tw10)
        self.tw10_price.setGeometry(QtCore.QRect(830, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        font.setBold(True)
        self.tw10_price.setFont(font)
        self.tw10_price.setObjectName("tw10_price")
        self.tw10_price.setStyleSheet("color:#678090")









        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(8, 4, 191, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")



        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tw1_dev.setText(_translate("MainWindow", "developer"))
        self.tw1_name.setText(_translate("MainWindow", "Game Name"))
        self.tw1_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw1_tags.setText(_translate("MainWindow", "标签："))
        self.tw1_or.setText(_translate("MainWindow", "总体评价："))
        self.tw1_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw1_img.setText(_translate("MainWindow", "IMG"))
        self.tw1_price.setText(_translate("MainWindow", "￥233"))

        self.tw2_dev.setText(_translate("MainWindow", "developer"))
        self.tw2_name.setText(_translate("MainWindow", "Game Name"))
        self.tw2_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw2_tags.setText(_translate("MainWindow", "标签："))
        self.tw2_or.setText(_translate("MainWindow", "总体评价："))
        self.tw2_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw2_img.setText(_translate("MainWindow", "IMG"))
        self.tw2_price.setText(_translate("MainWindow", "￥233"))

        self.tw3_dev.setText(_translate("MainWindow", "developer"))
        self.tw3_name.setText(_translate("MainWindow", "Game Name"))
        self.tw3_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw3_tags.setText(_translate("MainWindow", "标签："))
        self.tw3_or.setText(_translate("MainWindow", "总体评价："))
        self.tw3_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw3_img.setText(_translate("MainWindow", "IMG"))
        self.tw3_price.setText(_translate("MainWindow", "￥233"))

        self.tw4_dev.setText(_translate("MainWindow", "developer"))
        self.tw4_name.setText(_translate("MainWindow", "Game Name"))
        self.tw4_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw4_tags.setText(_translate("MainWindow", "标签："))
        self.tw4_or.setText(_translate("MainWindow", "总体评价："))
        self.tw4_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw4_img.setText(_translate("MainWindow", "IMG"))
        self.tw4_price.setText(_translate("MainWindow", "￥233"))

        self.tw5_dev.setText(_translate("MainWindow", "developer"))
        self.tw5_name.setText(_translate("MainWindow", "Game Name"))
        self.tw5_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw5_tags.setText(_translate("MainWindow", "标签："))
        self.tw5_or.setText(_translate("MainWindow", "总体评价："))
        self.tw5_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw5_img.setText(_translate("MainWindow", "IMG"))
        self.tw5_price.setText(_translate("MainWindow", "￥233"))

        self.tw6_top.setText(_translate("MainWindow", "Top 6"))
        self.tw6_name.setText(_translate("MainWindow", "Game Name"))
        self.tw6_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw6_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw6_price.setText(_translate("MainWindow", "￥233"))

        self.tw7_top.setText(_translate("MainWindow", "Top 7"))
        self.tw7_name.setText(_translate("MainWindow", "Game Name"))
        self.tw7_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw7_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw7_price.setText(_translate("MainWindow", "￥233"))

        self.tw8_top.setText(_translate("MainWindow", "Top 8"))
        self.tw8_name.setText(_translate("MainWindow", "Game Name"))
        self.tw8_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw8_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw8_price.setText(_translate("MainWindow", "￥233"))

        self.tw9_top.setText(_translate("MainWindow", "Top 9"))
        self.tw9_name.setText(_translate("MainWindow", "Game Name"))
        self.tw9_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw9_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw9_price.setText(_translate("MainWindow", "￥233"))

        self.tw10_top.setText(_translate("MainWindow", "Top 10"))
        self.tw10_name.setText(_translate("MainWindow", "Game Name"))
        self.tw10_or_text.setText(_translate("MainWindow", "UNKNOW"))
        self.tw10_tags_text.setText(_translate("MainWindow", "TAG1 TAG2 TAG 3 TAG 4......"))
        self.tw10_price.setText(_translate("MainWindow", "￥233"))



        self.label_2.setText(_translate("MainWindow", "Steam推荐 - Top10 Game"))
